#!/usr/bin/env bash
ENV_VAR_PREFIX="ROOTBEER_"

# Slack webhook settings
SLACK_CHANNEL="#rootbeer"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/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"
ICON_URL="https://github.com/scottyab/rootbeer/raw/master/app/src/main/res/mipmap-xhdpi/ic_launcher.png"

# Git info
GIT_URL="https://github.com/scottyab/rootbeer"
GIT_TAG=`git name-rev --name-only --tags HEAD`
GIT_COMMIT_DESC=`git log -n 1 $CIRCLE_SHA1`
GIT_CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

# Settings for github releases
GITHUB_RELEASE_NAME="Rootbeer"
GITHUB_RELEASE_MODULE="rootbeerlib"
GITHUB_RELEASE_DESC="This release was automatically generated by the CI server"
GITHUB_RELEASE_URL="https://api.github.com/repos/scottyab/rootbeer/releases"
GITHUB_RELEASE_TOKEN=$ROOTBEER_GITHUB_RELEASE_TOKEN
GITHUB_UPLOAD_URL="https://uploads.github.com/repos/scottyab/rootbeer/releases/"
GITHUB_RELEASE_FILE_PATH="app/build/outputs/apk/release/app-release.apk"
GITHUB_RELASE_FILENAME="Rootbeer.apk"

# App name for webhook
APP_RELEASE_NAME="RootBeer Sample App"


# Fires a webhook to slack to notify of successful upload to beta
function webhook {

    gradle_app_name="$1"
    app_name="$2"
    message="$3"
    git_hash=`git rev-parse --short HEAD`
    version=`cat ${gradle_app_name}/build.gradle | grep -m 1 versionName | cut -d'"' -f 2`
    
    echo $message
    echo $channel $gradle_app_name $app_name $version $ICON_URL

    curl -X POST --data-urlencode 'payload={"channel": "'"$SLACK_CHANNEL"'", "username": "CirclCI Deployment Bot", "text": "*'"$app_name"'* version *'"$version"'*  <'"$GIT_URL/commits/$git_hash"'|'"$git_hash"'> '"$message"'", "icon_url": "'"$ICON_URL"'"}' $SLACK_WEBHOOK_URL

}  
